### ISSUE TITLE
Announce the Game on Mutiple Channels

### ISSUE THREAD

**Issue by Indy2222** [DigitalExtinction/Game#120]
Make sure not to go against community rules in any of the listed channels.

- [x] [/r/gamedev/](https://www.reddit.com/r/gamedev/)
- [x] [/r/rust](https://www.reddit.com/r/rust/) -> [Digital Extinction a 3D real-time strategy game made with Rust and Bevy](https://www.reddit.com/r/rust/comments/10r1fhh/digital_extinction_a_3d_realtime_strategy_game/)
- [x] [/r/bevy](https://www.reddit.com/r/bevy/) -> [here](https://www.reddit.com/r/bevy/comments/y18p0x/digital_extinction_a_3d_rts_game_build_with_bevy/)
- [ ] [This Week in Rust](https://this-week-in-rust.org/)
- [ ] [/r/linux_gaming/](https://www.reddit.com/r/linux_gaming/)
- [x] [/r/opensourcegames/](https://www.reddit.com/r/opensourcegames/) -> [Digital Extinction a GPL Licensed 3D RTS Game (WIP)](https://www.reddit.com/r/opensourcegames/comments/10r1143/digital_extinction_a_gpl_licensed_3d_rts_game_wip/)
- [x] Twitter, mention [@bevyengine](https://twitter.com/bevyengine) -> [here](https://twitter.com/MartinIndra92/status/1620835130410676225) and on other occasions.
- [x] [Bevy Assets](https://github.com/bevyengine/bevy-assets) -> [bevyengine/bevy-assets#266](https://github.com/bevyengine/bevy-assets/pull/266)
- [x] [Rust Gamedev Newsletter](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/1180) -> [rust-gamedev/rust-gamedev.github.io/#1190](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1190)
- [x] Are we games yet? -> [rust-gamedev/arewegameyet/#513](https://github.com/rust-gamedev/arewegameyet/pull/513)
