### ISSUE TITLE
Path Towards Version 0.1

### ISSUE THREAD

**Issue by Indy2222** [DigitalExtinction/Game#246]
This is a tracking ticket organizing work towards the release of version 0.1. See [the roadmap](https://github.com/DigitalExtinction/Game#roadmap) for more information about the version.

# 3D Graphics & Related

- [ ] Overall artistic / visual style of the game. This is related to #238.
- [ ] 3D models of all elementary units & buildings. This includes the models, texture / surface colors, animations) #238

# Music & Sound

- [ ] Minimum sound set: laser fires, unit destruction, ...

# UI

- [ ] Game UI: minimap, manufacturing menu
- [ ] Mouse cursors

TODO
