### ISSUE TITLE
Energy Tracking Issue

### ISSUE THREAD

**Issue by Indy2222** [DigitalExtinction/Game#256]
This is a tracking issue for the implementation of the game energy system (see [DESIGN.md](https://github.com/DigitalExtinction/Game/blob/main/DESIGN.md)).

- [ ] Batteries - can be charged and drained. All buildings and units have one (with a maximum capacity). One the battery dies, the unit / building becomes completely inactive.
- [ ] Electricity grid: lasers & electricity panels. Create infrastructure for transmission over the grid.
- [ ] Power plants - produce energy and transmit it to energy sinks with highest need.
  - The transmission optimization is related to the [maximum flow problem](https://en.wikipedia.org/wiki/Maximum_flow_problem)

**Comment by JackCrumpLeys** [comment]
Basic battery merged #473
