### ISSUE TITLE
Improve & Document Code Structure

### ISSUE THREAD

**Issue by Indy2222** [DigitalExtinction/Game#266]
# TODO

- [x] Extend / update `CONTRIBUTING.md` to contain the following structure.
- [ ] Adapt the code based on the guidelines.
- [ ] Update & extend crate level documentation.

# Structure

* Game functionality is split into many small crates with hundreds to thousands SLOC.
* Keep public API of each crate at minimum.
* Whenever feasible, the public API consists solely of events and system labels.
  * Documentation of each event contains:
    * stage in which the event originates / is consumed
    * system label (possibly labeling multiple systems) of the systems which send/consume the event
* Crate public API may expose components, however components may be inserted, removed or mutated solely from their respective crates. 
* event struct names end with `Event`
* label enum names end with `Label`
