### ISSUE TITLE
In-game Networking Tracking Issue

### ISSUE THREAD

**Issue by Indy2222** [DigitalExtinction/Game#569]
- [x] New entity spawning
  - #710
- [x] Entity despawning (destruction)
  - #710
- [x] Entity path synchronization
  - #737
- [x] Translation synchronization
  - #736
- [x] Health synchronization
  - #729
