### ISSUE TITLE
Public Announcement of the Game

### ISSUE THREAD

**Issue by Indy2222** [DigitalExtinction/Game#60]
- [ ] MVP Milestone: https://github.com/DigitalExtinction/Game/milestone/1
- [x] #37
- [x] #71
- [x] #72
- [x] #73
- [x] create Matrix or Discord room / space
  - https://discord.gg/vHMFuCWGSX
- [x] #88
- [x] #86
- [x] #120
- [x] #38
- [x] Add `Roadmap` section to `README.md` - link this to milestones
- [x] publish version 0.0.1 of the crates to crates.io so no bot can steal the name
